import type { Language } from './i18n/types';

export const MATH_TIPS_EN = [
  'Zero means nothing, but it helps us write bigger numbers like 10 and 100!',
  'When you count, each number is one more than the number before it.',
  'You can count on your fingers — ten fingers can show any number from 0 to 10!',
  'Adding means putting groups together to find how many in all.',
  'Subtracting means taking away to find how many are left.',
  'Doubles are easy to remember: 3 + 3 = 6, 4 + 4 = 8, and 5 + 5 = 10!',
  'Even numbers can be split into two equal groups. Odd numbers leave one left over.',
  'A triangle has 3 sides, a square has 4, and a circle has no corners at all!',
  'Patterns repeat — like red, blue, red, blue. Can you guess what comes next?',
  'The number line goes left for smaller numbers and right for bigger numbers.',
  '10 ones make 1 ten. That is why 10 looks like a 1 and a 0 together!',
  'When adding 9 to a number, try adding 10 first, then take away 1.',
  'Counting by 2s skips every other number: 2, 4, 6, 8, 10…',
  'Counting by 5s lands on numbers that end in 0 or 5: 5, 10, 15, 20…',
  'Counting by 10s lands on 10, 20, 30 — the ones digit stays at 0!',
  'Multiplication is a fast way to add the same number again and again.',
  '3 × 4 means three groups of four, or 4 + 4 + 4 = 12.',
  'Any number times 0 equals 0. Any number times 1 stays the same!',
  'Division splits a number into equal groups. How many in each group?',
  'Half means two equal parts. One half of 8 is 4.',
  'A fraction shows parts of a whole. 1/2 means one part out of two equal parts.',
  'The top of a fraction tells how many parts you have. The bottom tells how many equal parts in all.',
  'Shapes with four equal sides and four corners are called squares.',
  'A rectangle has four sides too, but not all sides need to be the same length.',
  'A cube is like a box — it has 6 flat faces, all squares!',
  'Measuring with your hand span or footsteps is a fun way to compare lengths.',
  'Bigger numbers are not always scarier — break them into tens and ones!',
  'In 23, the 2 means 2 tens (20) and the 3 means 3 ones.',
  'Round numbers end in zero. 20, 30, and 100 are all round numbers!',
  'Comparing numbers: the one farther right on the number line is bigger.',
  'The equals sign (=) means both sides have the same amount.',
  'A plus (+) sign means add. A minus (−) sign means take away.',
  'You can check addition by counting back with subtraction.',
  'Making ten is a handy trick: 8 + 5 = 8 + 2 + 3 = 10 + 3 = 13.',
  'Symmetry means both sides look the same, like a butterfly’s wings!',
  'A clock face is a circle divided into 12 equal parts for the hours.',
  'An hour has 60 minutes. Half an hour is 30 minutes.',
  'Money math uses decimals: RM 1.50 means one ringgit and fifty sen.',
  'Sorting objects by size, colour, or shape is math too!',
  'A bar graph uses bars to show which group has more or less.',
  'Estimating means making a smart guess before you count exactly.',
  'Practice a little every day — your brain gets stronger like a muscle!',
  'Mistakes help you learn. Every wrong try teaches you something new.',
  'Drawing pictures can help solve story problems — show the groups!',
  'If 5 + ? = 9, you can think: what do I add to 5 to reach 9?',
  'Skip counting helps you multiply faster later on.',
  'Three twos make six: 2 + 2 + 2 = 6, so 3 × 2 = 6.',
  'A quarter (1/4) means one part when something is cut into four equal pieces.',
  'Two quarters make a half — that is 1/4 + 1/4 = 2/4 = 1/2!',
  'Math is everywhere: in games, cooking, shopping, and even in music!',
] as const;

export const MATH_TIPS_MS = [
  'Sifar bermaksud tiada, tetapi ia membantu kita menulis nombor lebih besar seperti 10 dan 100!',
  'Apabila anda kira, setiap nombor adalah satu lebih daripada nombor sebelumnya.',
  'Anda boleh kira dengan jari — sepuluh jari boleh tunjuk nombor 0 hingga 10!',
  'Tambah bermaksud gabungkan kumpulan untuk cari jumlah keseluruhan.',
  'Tolak bermaksud ambil pergi untuk cari berapa yang tinggal.',
  'Nombor kembar mudah diingat: 3 + 3 = 6, 4 + 4 = 8, dan 5 + 5 = 10!',
  'Nombor genap boleh dibahagikan kepada dua kumpulan sama. Nombor ganjil tinggal satu.',
  'Segi tiga ada 3 sisi, segi empat ada 4, dan bulatan tiada penjuru langsung!',
  'Corak berulang — seperti merah, biru, merah, biru. Boleh teka yang seterusnya?',
  'Garis nombor pergi kiri untuk nombor kecil dan kanan untuk nombor besar.',
  '10 satu jadi 1 puluh. Itu sebab 10 nampak macam 1 dan 0 bersama!',
  'Bila tambah 9, cuba tambah 10 dulu, kemudian tolak 1.',
  'Kira langkau 2 melangkau nombor: 2, 4, 6, 8, 10…',
  'Kira langkau 5 berakhir dengan 0 atau 5: 5, 10, 15, 20…',
  'Kira langkau 10: 10, 20, 30 — digit satu kekal 0!',
  'Pendaraban cara cepat untuk tambah nombor yang sama berulang kali.',
  '3 × 4 bermaksud tiga kumpulan empat, atau 4 + 4 + 4 = 12.',
  'Apa-apa nombor darab 0 sama dengan 0. Darab 1 nombor kekal sama!',
  'Pembahagian bahagikan nombor kepada kumpulan sama. Berapa setiap kumpulan?',
  'Separuh bermaksud dua bahagian sama. Separuh daripada 8 ialah 4.',
  'Pecahan tunjuk bahagian daripada keseluruhan. 1/2 bermaksud satu bahagian daripada dua sama.',
  'Atas pecahan tunjuk berapa bahagian anda ada. Bawah tunjuk berapa bahagian sama keseluruhan.',
  'Bentuk dengan empat sisi sama dan empat penjuru dipanggil segi empat sama.',
  'Segi empat tepat ada empat sisi juga, tapi tidak semua sisi sama panjang.',
  'Kiub macam kotak — ada 6 muka rata, semua segi empat sama!',
  'Ukur dengan tapak tangan atau langkah kaki cara seronok bandingkan panjang.',
  'Nombor besar tidak menakutkan — pecahkan kepada puluh dan satu!',
  'Dalam 23, 2 bermaksud 2 puluh (20) dan 3 bermaksud 3 satu.',
  'Nombor bulat berakhir dengan sifar. 20, 30, dan 100 semua nombor bulat!',
  'Banding nombor: yang lebih kanan pada garis nombor lebih besar.',
  'Tanda sama dengan (=) bermaksud kedua-dua belah jumlah sama.',
  'Tanda tambah (+) bermaksud tambah. Tanda tolak (−) bermaksud ambil pergi.',
  'Anda boleh semak tambah dengan tolak balik.',
  'Buat sepuluh tip berguna: 8 + 5 = 8 + 2 + 3 = 10 + 3 = 13.',
  'Simetri bermaksud kedua-dua belah kelihatan sama, macam sayap rama-rama!',
  'Muka jam bulatan dibahagikan 12 bahagian sama untuk jam.',
  'Satu jam ada 60 minit. Separuh jam ialah 30 minit.',
  'Matematik wang guna perpuluhan: RM 1.50 bermaksud satu ringgit lima puluh sen.',
  'Susun benda mengikut saiz, warna, atau bentuk pun matematik!',
  'Graf bar guna bar tunjuk kumpulan mana lebih atau kurang.',
  'Anggaran bermaksud teka bijak sebelum kira tepat.',
  'Latih sedikit setiap hari — otak anda jadi kuat macam otot!',
  'Kesilapan bantu anda belajar. Setiap cubaan salah ajar sesuatu baru.',
  'Lukis gambar boleh bantu selesaikan soalan cerita — tunjuk kumpulan!',
  'Jika 5 + ? = 9, fikir: tambah apa pada 5 untuk sampai 9?',
  'Kira langkau bantu anda darab lebih cepat nanti.',
  'Tiga dua jadi enam: 2 + 2 + 2 = 6, jadi 3 × 2 = 6.',
  'Suku (1/4) bermaksud satu bahagian bila sesuatu dipotong empat sama.',
  'Dua suku jadi separuh — 1/4 + 1/4 = 2/4 = 1/2!',
  'Matematik ada di mana-mana: permainan, masakan, beli-belah, dan muzik!',
] as const;

export function getMathTips(lang: Language): readonly string[] {
  return lang === 'ms' ? MATH_TIPS_MS : MATH_TIPS_EN;
}
